### ISSUE TITLE
Alternative download source

### ISSUE THREAD

**Issue by IzzySoft** [communitymedia/mediaphone#11]
Would you consider making your app available outside Play Store as well (e.g. attaching the APK to `releases/`, or even bringing the app to [F-Droid](https://f-droid.org/) – so folks without Playstore access can use it as well?

**Comment by simonrob** [comment]
Happy to do that - I've edited the 1.6.1 release to include the [APK](https://github.com/communitymedia/mediaphone/releases/download/v1.6.1/mediaphone-v1.6.1.apk).

F-Droid is also a possibility, but it would be great if you could help with the process for submitting the app there.

**Comment by IzzySoft** [comment]
Thanks a lot! For a quick start, I've just added your app to my F-Droid repo – it will [show up here](https://apt.izzysoft.de/fdroid/index/apk/ac.robinson.mediaphone) with the next sync in about 8 hours.

For inclusion with F-Droid.org, I gladly assist as well (disclosure: I'm one of the maintainers there). I'd suggest you start by establishing [Fastlane file structure](https://gitlab.com/snippets/1895688) in your repo (at least the basics; minimum would be `short_description.txt` and `full_description.txt`; to improve add the screenshots, if you can also per-release changelogs; ideally for multiple languages, but `en-US` should be there and suffices – your users could then provide additional languages via PRs here and they'd be picked up with the next release automatically). That done, [open an RFP](https://gitlab.com/fdroid/rfp/issues) and I'd pick up from there.

**Comment by simonrob** [comment]
I've added the Fastlane metadata with screenshots in a349ccd (and Gradle distributionSha256Sum in d15fb4e).

Please could you take a look?

**Comment by IzzySoft** [comment]
Wow… :dog: :dog2: :service_dog: So many languages! :smile:

But better remove the `<br>` at the end of each line in `full_description.txt` – this will look ugly otherwise at least in F-Droid, as each new-line is replaced by an `<br>` as well. You can make use of other HTML tags though if you like, e.g. `<a href` for the URLs. Things like B and I are possible, too.

Apart from that: looks great! Let me know when you declare it "ready", so I already pull it for my repo. And definitely let me know should you add per-release changelogs, as my updater would pull those along with the APK if I tell it to do so :wink:

**Comment by simonrob** [comment]
Thanks for taking a look.

The `<br>` is for formatting in the Google Play store listing, as that is pretty much the only way to reliably create paragraphs on both the app and website versions. Similarly, the URLs are plain text because `<a>` tags are stripped, whereas plain text links are left in place. As Google Play is the primary distribution platform, I'm just [copying these over](https://github.com/communitymedia/mediaphone/blob/master/fastlane/xmltofastlane.py) to the fastlane format on every build, rather than writing new custom versions.

Re: changelogs, can you scrape them from the GitHub releases page like you do for the APK?

I think it's ready enough for now, but I'll take a look once it has been pulled and can always refine in a future version (assuming you pull everything each time a new release is created).

**Comment by IzzySoft** [comment]
OK, fine with me. No idea how `fastlane supply` deals with that (I don't use Play Store), so I just pointed it out from the "F-Droid point-of-view".

No, I cannot scrape the changelogs from `releases/`, sorry. I considered that from time to time, but then I'd need a quite sophisticated parser (you might not be aware of what some projects put there).

A second no, unfortunately, to "continuous pull". F-Droid itself does that, but building from source the update mechanism is completely different from mine (to build, you need to checkout the entire repo anyway – while I basically only pick the APKs). But yes, I can pull it once now (so you see how it will look, at least when using the Android app) – and I can pull it again if you tell me to, if it's not too frequent :smile:

I'll hurry with the first pull now, as in half an hour my updater starts. So results should be publically visible in about an hour.

**Comment by IzzySoft** [comment]
Done. Not sure if the links will be rendered at all in the F-Droid app. If not, you could simply put the URL into href as well as the "plain text" :wink:

**Comment by simonrob** [comment]
Thanks!

In 070fb2f I've updated the `full_description.txt` files for better formatting, and added a changelog for recent versions. Please could you pull again?

Finally, just to clarify: will this now be propagated to the default F-Droid repository, or is there an additional step?

**Comment by IzzySoft** [comment]
Done, also pulled the changelog (which will from now on be pulled automatically).

There is no automated propagation. To get it into the repo at f-droid.org, you can simply [open an RFP](https://gitlab.com/fdroid/rfp/issues), I'd pick up from there then.

**Comment by simonrob** [comment]
I've submitted an [RFP](https://gitlab.com/fdroid/rfp/-/issues/1358). Let's move any further discussion there if needed. Thanks for the help so far.
