### ISSUE TITLE
Content scalation issues in HTML exporting

### ISSUE THREAD

**Issue by EchedelleLR** [communitymedia/mediaphone#13]
I am reporting here from a friend's experience.

It seems to happen with any content, not only text.

Webview based:
![image-2242486116](https://user-images.githubusercontent.com/56733813/97092942-e96e4200-163f-11eb-926b-235aa517a939.jpg)
![image-522969602](https://user-images.githubusercontent.com/56733813/97093782-d57a0e80-1646-11eb-9a5b-9228ba861e51.jpg)

IceCat based:
![image-1562455413](https://user-images.githubusercontent.com/56733813/97093786-dd39b300-1646-11eb-8eed-57b7f57cd0e6.jpg)

**Comment by simonrob** [comment]
Thanks for reporting this.

I can't replicate the WebView results that you are seeing, but I presume this is happening in an app that overrides the viewport (which isn't actually specified in the HTML player).

To be honest the HTML export option is primarily aimed at non-mobile browsers. I could update it to fix this, but would probably lose some of the backwards compatibility that Com-Phone tries to preserve. I will take a look.

Is your friend using a recent phone? What version of Android do they have?

**Comment by EchedelleLR** [comment]
The Webview tests were made from a webapp which uses the webview in raw to render HTML/CSS and allow JS content as the Android default web browser cannot open files and HTML viewer cannot execute JS by default (https://github.com/Simon-Laux/ZHV)

Android version is Android 9.

**Comment by EchedelleLR** [comment]
I think it overrides viewport for mobile screen adaptation as most webpages are not adapted to the mobile screen (see IceCat example very very very far to be read correctly) and ZHV is integrated in a version of Delta Chat used by Cubans to interact dynamically with a bot and allow deep actions as web browsing, etc.

**Comment by simonrob** [comment]
Please can you try this sample of a new HTML narrative player and let me know whether it is a better experience: https://digitaleconomytoolkit.org/com-phone/beta/com-phone-4f20230d.html

**Comment by EchedelleLR** [comment]
I tried to download it on mobile directly but seems that was difficult to find a browser which allowed it and also was downloaded broken...

Could you upload it attached here? If not I can try in the computer later.

**Comment by simonrob** [comment]
You shouldn't need to download it - it plays in the browser automatically.

However, if you want to try it in a different app that needs a local file, the following link should automatically download rather than playing: https://digitaleconomytoolkit.org/com-phone/beta/download/com-phone-4f20230d.html

**Comment by EchedelleLR** [comment]
It works perfectly. Thank you.
![Screenshot_20201029-095636](https://user-images.githubusercontent.com/56733813/97553388-474ab300-19cd-11eb-9db6-fa026d49b9f1.png)
![Screenshot_20201029-095639](https://user-images.githubusercontent.com/56733813/97553394-487be000-19cd-11eb-8e0e-34714a34a8a4.png)
![Screenshot_20201029-095629](https://user-images.githubusercontent.com/56733813/97553396-49ad0d00-19cd-11eb-8cdf-ea68ab9dc4d9.png)
![Screenshot_20201029-095706](https://user-images.githubusercontent.com/56733813/97553399-4a45a380-19cd-11eb-9837-53f0a4527d15.png)

**Comment by EchedelleLR** [comment]
I have a new issue. Idk if report here or other part.

**Comment by simonrob** [comment]
Fixed in [`mediautilities 30dc950`](https://github.com/communitymedia/mediautilities/commit/30dc950). Moving discussion of audio playback to #15.
