### ISSUE TITLE
Allow set autoplay in HTML exporting

### ISSUE THREAD

**Issue by EchedelleLR** [communitymedia/mediaphone#14]
This is more a feature request.

A friend told me that would like to export the HTML version with autoplaying possibility which is allowed itself.

**Comment by simonrob** [comment]
This is currently not supported as it would mean that audio playback would not work (see [reason](https://hacks.mozilla.org/2019/02/firefox-66-to-block-automatically-playing-audible-video-and-audio/) - this is now the case in most browsers). However, touching or clicking anywhere on the screen should start playback. I would also be happy to take a pull request (see `res/raw/html_player.html`) that achieves this without significant extra code.

**Comment by EchedelleLR** [comment]
Thank you for the explanation.
