### ISSUE TITLE
Audio not played correctly

### ISSUE THREAD

**Issue by EchedelleLR** [communitymedia/mediaphone#15]
This is an issue detected while checking https://github.com/communitymedia/mediaphone/issues/13. 

It seems that audio are not played if the narrative is played from the beginning. 

As pointed a friend, if you start playing from the part containing the audio, this one is played correctly and if, after that, you re-play the narrative, the audio is played correctly.

**Comment by EchedelleLR** [comment]
After a fast test in a desktop browser, this only happens in mobile, both using custom app based on the webview and a normal browser which also uses the webview like default Android web browser being, this issue, not reproducible, in Firefox Fenix which plays it correctly on mobile.

**Comment by simonrob** [comment]
Thanks for spotting this issue! Please can you try the updated versions below (they are identical). For me this change fixes the issue.

- Online playback: https://digitaleconomytoolkit.org/com-phone/beta/com-phone-67fa008c.html
- Downloadable: https://digitaleconomytoolkit.org/com-phone/beta/download/com-phone-67fa008c.html

As an aside, I did wonder whether this approach would permit autoplay as requested in #14, but sadly not - most browsers block autoplay unless muted (which defeats the point).

**Comment by EchedelleLR** [comment]
I tested it with my friend and works perfectly now.

**Comment by simonrob** [comment]
Great - glad to hear it!

This change will be included in the next version of the app - hopefully within the next week or so.
