### ISSUE TITLE
Feature request: Add posibility to attach global audio

### ISSUE THREAD

**Issue by EchedelleLR** [communitymedia/mediaphone#16]
This use to be the cases of a background music or general explanation.

I am not sure if would be better a new level in which an audio can be attached to more than one section or just a global option for all the narrative.

**Comment by simonrob** [comment]
I'm not quite sure I understand this fully, but if you're referring to having audio span the whole narrative (or subsections of it), you can enable this advanced feature in the app's settings. See the attached images where I've added highlights in green: tick the box to enable spanning media, and then use the new button that appears in each media type's edit screen.
![settings](https://user-images.githubusercontent.com/934006/97706489-b4ce1080-1aad-11eb-9b10-d0b95e69910d.png)
![spanning](https://user-images.githubusercontent.com/934006/97706504-ba2b5b00-1aad-11eb-9253-4c6668d604bc.png)

**Comment by EchedelleLR** [comment]
Thank you. I didn't know.

What is about enabling a audio for 2 or more frames but not all the narrative? I mean, the possibility that 2 or more frames can share the same audio file but afther or before them could exist other frames with different audio files or no audio files.

**Comment by simonrob** [comment]
Yes, this is possible. If you want to have a different audio file after one that spans multiple frames, just go to the place you want to insert it and edit as normal. You will be prompted about whether you want to edit the original item or add a new one - just choose to add a new one.

This spanning capability works for all media types - i.e., audio, images and text. Setting the stop position without adding replacement media is not formally supported, but an easy way to achieve this is to follow the same procedure as adding a new item and instead add a non-spanning media item that won't be noticed.

For images and text, just add a new item on the last spanning frame that uses the same media but is set to not span. For audio it is slightly harder, but the easiest way to achieve this is to just add something that won't be heard - e.g., press start/stop recording quickly to record a few milliseconds of silence.

It would require quite a bit of extra work to support setting start/stop points for media without over-complicating the interface, but I'd be happy to take suggestions or pull requests.

**Comment by EchedelleLR** [comment]
Thank you for the information. I think this can be closed then and I could re-open if I think I have something to add.
