### ISSUE TITLE
[Feature Req] Video frames

### ISSUE THREAD

**Issue by anaskaejdar** [communitymedia/mediaphone#18]
Social media stories typically can handle video afaik.  I'm not all that hip with the big social media silos, but I know instagram can handle video in stories.  Seems right now com-phone can only take photos as frames, not videos.

I've had this app installed for a while because I liked the idea of it, but I hadn't had a use for it until today.  But my source material are all videos, so I couldn't actually use comphone for my purpose.  That was a bummer.

**Comment by simonrob** [comment]
This feature is something that is relatively commonly requested. However, I'm quite firmly of the opinion that it is out of scope for this app.

The reason for this is that Com-Phone is focused on creating digital stories with an interface that is as simple as possible. Adding video would probably increase its complexity significantly.

I'd probably be happy to consider pull requests that achieve this without compromising the simplicity of the app (or indeed its small APK size - simply integrating ffmpeg won't be accepted). This could be achieved via one of the advanced feature switches in the app's settings, perhaps, just like the existing multi-frame media and timing editor ones. However, I won't be implementing this myself.

Please note that there are many apps on Google Play that **do** provide this functionality, so hopefully you're able to find one that works for your use-case.
