### ISSUE TITLE
mediaphone [1.5.2] Failed to import music in m4a format

### ISSUE THREAD

**Issue by Icramss** [communitymedia/mediaphone#2]
# Expected behavior

This app can import any kind of music

# Actual behavior

It turned out that import music in m4a format failed

# How to reproduce

- Download app on playstore
- Provide music in m4a format in your filemanager.
- Open the Com-phone app
- Tap ➕ to add a new frame
- Tap 🔊 to select music files
- Tap 🎵 to select music
- Tap on the m4a music format you have prepared earlier
- Click OK. Your import failed

### Device: ONE PLUS 2 OxygenOS Version 3.6.1
Operating System:Android 6.0.1
App Version :1.5.1

# Recording of the bug

https://youtu.be/0H8RemYPGfw

**Comment by simonrob** [comment]
Thanks for this report.

Please could you provide a sample m4a file that doesn't work for you?

**Comment by Icramss** [comment]
Wait , i will provide for you.

**Comment by Icramss** [comment]
https://drive.google.com/file/d/1PdEiQ9sFV3j43c0eYPnNVecJhdXpJQVz/view?usp=drivesdk

This is one of my music.
I was share it on Drive

**Comment by simonrob** [comment]
Thanks for sharing a sample. However, this file imports into Com-Phone with no issues for me. I'll need to be able to replicate this before I can solve the issue for you.
