### ISSUE TITLE
Com-phone [1.5.2] Multiphoto selection is not work

### ISSUE THREAD

**Issue by Icramss** [communitymedia/mediaphone#3]
# Expected behavior

Multiphoto must work. Excerpted from the reply of the project owner to comments on the playstore, this App supports multiphoto selection

# Actual behavior

After selecting some photos and clicking OK, they will not work. He returned to the camera

# How to reproduce

- Download app on playstore
- Open the Com-phone app
- Tap ➕ to add a new frame
- Tap Camera icon to add photos
- Tap the photo icon on the left side
- please select some photos and click ✔️ at the top to add.
- It does not work. He returned to the camera

### Device: ONE PLUS 2 OxygenOS Version 3.6.1
Operating System:Android 6.0.1
App Version :1.5.1

# Recording of the bug

https://youtu.be/9-ns8fVc2dg

**Comment by simonrob** [comment]
Thanks for this report. I'm unable to replicate the issue, however.

Please can you try importing just one photo - does this work for you?

**Comment by Icramss** [comment]
You can see on the URL of youtube. I was provided for you

**Comment by simonrob** [comment]
The video shows importing multiple photos, but does not show the photo or any error message. I'm trying to track down why this might be the case, so if you can try importing a single photo and letting me know whether that works it would be very helpful.

**Comment by Icramss** [comment]
Select a photo is work

**Comment by simonrob** [comment]
In that case, I can't yet replicate the issue. Are you selecting the photos from the camera, or another location?

**Comment by Icramss** [comment]
I am select the pictures in galery by click gallery icon in the left when i am in camera feature

**Comment by sachincool** [comment]
Hey @simonrob  I got the same problem, 
![](https://cdn.discordapp.com/attachments/397972978933170178/451801930147168278/20180531_230849.gif) Here is my gif. Might come in handy.
 The bug exists in choosing pictures from Gallery.
I was not able to choose single or multiple images.  
But it was successful from the camera.

**Comment by simonrob** [comment]
Thanks @sachincool - this helps. Reopening as clearly something isn't working properly here. I'll come back to this issue with a fix when I can replicate it myself.

**Comment by simonrob** [comment]
@sachincool - please can you let me know what phone make and model you have, and what version of Android you are using?

**Comment by sachincool** [comment]
Mi 5 Android 7.0 @simonrob
