### ISSUE TITLE
When i create a Narrative with file music of duration 32 minutes ,Export by HTML ( create a web page) is fail. 

### ISSUE THREAD

**Issue by Icramss** [communitymedia/mediaphone#4]

**Comment by simonrob** [comment]
Thanks for this feedback.

To be honest, the HTML export option is unmaintained, and probably seldom used. It uses the same methodology as the other export options, however, so should work similarly.

Does the 32 minute narrative export successfully as a video file?

**Comment by Icramss** [comment]
It also does not work. I need to give a recording!

**Comment by simonrob** [comment]
Ok, I'd like to fix this then.

Is your 32 minutes of audio something that you've imported, or a narration that you've recorded directly using Com-Phone?

**Comment by Icramss** [comment]
Yeah , i am com-phone

**Comment by simonrob** [comment]
Ok - I'll look into this and see whether I can replicate the issue.

In the meantime, you can export your narrative using the SMIL option, which will produce both a webpage and SMIL movie, and will include all of the components in their original format.

**Comment by Icramss** [comment]
Please let me know if you can replicate it

**Comment by simonrob** [comment]
I've tried to replicate this issue with a 37 minute audio recording in Com-Phone. While the HTML option doesn't work, exporting as a video completes with no issues. Please can you give me more information about the structure of the narrative you are trying to export that is causing these issues?

**Comment by Icramss** [comment]
I will give you the detail of this problem with the near future.

**Comment by simonrob** [comment]
The latest version of Com-Phone (1.5.2) fixes this issue. Thanks for reporting and helping source the problem!
