### ISSUE TITLE
Export video to whatsapp is not support

### ISSUE THREAD

**Issue by Icramss** [communitymedia/mediaphone#6]

**Comment by simonrob** [comment]
This is not currently something that Com-Phone is able to support - we use .mov as the video format as it can be generated on mobile devices without needing large heavy duty native libraries (e.g., ffmpeg). One of the original aims of Com-Phone was to be lightweight and require very little storage space; currently this is still an issue in many usage contexts, so .mov will remain the video export format for the time being.

**Comment by simonrob** [comment]
An update on this - the newest version of Com-Phone (1.6 - 44141a9) supports MP4 video export, so you should be able to export to WhatsApp and other apps.
