### ISSUE TITLE
Com-phone v1.5.2 | Can not import music files downloaded by New Pipe app

### ISSUE THREAD

**Issue by Icramss** [communitymedia/mediaphone#7]

**Comment by simonrob** [comment]
Thanks for this report. I need a little more detail, however.

I'm not familiar with New Pipe, but from a quick search it looks like it is a YouTube client. Can you give me a little more detail about the files you're trying to import via this third-party app?

**Comment by Icramss** [comment]
# Actual behavior

failed to import downloaded music files with New pipe.

Newpipe is an application similar to youtube, but the newpipe app has many great features. One of them you can download video and audio from the application without the need of downloader application.

# How to reproduce

- Download the NewPipe app  on f-droid: https://f-droid.org/app/org.schabi.newpipe
- and run app
- find the music video you like
- Please Tap on the video to download.
- Tap download icon at the bottom of the video
- Select audio
- OK

Your music file will go into your device.

- Download Com-phone and install
- run app
- Tap➕ to add new frames
- Tap on camera icon to add image
- Click OK
- Then Tap 🔊 to add music files
- Tap 🎵 to add music from the device
- Please find the music file you downloaded from NewPipe application earlier.
- Tap on that music file
- Click OK
- you will see a failure message import operation

# Recording of the bug
You can watch my proof recording here 

https://youtu.be/NJ1bTsX84io

### Device: ONE PLUS 2 OxygenOS Version 3.6.1
Operating System:Android 6.0.1
App Version : 1.5.2
NewPipe version : 0.13.4

**Comment by simonrob** [comment]
Reopening as this hasn't yet been investigated.

**Comment by Icramss** [comment]
Are you can reproduce ?

**Comment by simonrob** [comment]
The original video and audio tracks are no-longer available. Please open a new issue if you experience this behaviour again.
